### ISSUE TITLE
Beeping sound keeps playing, even after exiting the vehicle

### ISSUE THREAD

**Issue by Druganov1** [matsn0w/IIS-EmergencyLS-ELS-FiveM#176]
I was tired of els-plus having countless bugs, so i switched to this one, however there are some concerning bugs that should be fixed.

**1. Warning beep keeps playing indefinetly after exiting vehicle.**

The first thing that was really annoying is that once you turn the stop sign on (REARREDS) and the warning beep is ticked, even if you exit the vehicle you will hear that beep untill you leave the server, or get into another car that has ELS, and toggle the stop sign.

**2. When you spawn a ELS vehicle, every extra is enabled by default**

The second very annoying thing that i discovered is that the moment you spawn a els vehicle, that you configured the VCF for, every extra on the vehicle will be enabled by default, i know this is not a bug in the resource itself as this is just build into FiveM, it would be nice to turn every extra off the moment someone sits in a vehicle for the first time.

**Comment by JustinRijsdijk** [comment]
Hi there @Druganov1 , at first, thanks for using miss-ELS! Thanks for submitting your issues. This helps us making MISS-ELS better!

Regarding your issues with the warning beep, we already have an outstanding issue on the current roadmap. Please see #173 if I'm not mistaken.

Regarding your point about all extras being on by default. I heard of a possible fix/workaround using the vehicle meta. I have not yet confirmed this myself, but it might be worth checking out; In your 'flags' section of your vehicles' meta file. There should be a flag called 'FLAG_EXTRAS_REQUIRE'. Can you try changing that into 'FLAG_EXTRAS_SCRIPT'? Please be sure to restart your server afterwards.

Please report back if this is indeed a fix/workaround for now.

**Comment by Druganov1** [comment]
> Hi there @Druganov1 , at first, thanks for using miss-ELS! Thanks for submitting your issues. This helps us making MISS-ELS better!
> 
> Regarding your issues with the warning beep, we already have an outstanding issue on the current roadmap. Please see #173 if I'm not mistaken.
> 
> Regarding your point about all extras being on by default. I heard of a possible fix/workaround using the vehicle meta. I have not yet confirmed this myself, but it might be worth checking out; In your 'flags' section of your vehicles' meta file. There should be a flag called 'FLAG_EXTRAS_REQUIRE'. Can you try changing that into 'FLAG_EXTRAS_SCRIPT'? Please be sure to restart your server afterwards.
> 
> Please report back if this is indeed a fix/workaround for now.

Hello there!


I have fixed every issue i named, made some improvements in the code itself,

Regarding that all the extras were on, i also fixed that within MISS-ELS.

How can i share the changes?

**Comment by matsn0w** [comment]
Hi, great to hear that your problems are fixed.

If you want to contribute, you can open a Pull Request with your code changes. We will review it and if approved, your code will be merged into our codebase. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request for a detailed explanation.
