### ISSUE TITLE
the els menu doesnt open if  i start the resource

### ISSUE THREAD

**Issue by therealnoskill** [matsn0w/IIS-EmergencyLS-ELS-FiveM#180]
i cant see an menu if i get in my car. dependencies installed ( warmenu) but i dont get the script work. can anyone help ? we would to change sirens in german but at first run with wm serversirens

**Additional context**
FiveM build: recommend
MISS ELS version: lates

**Comment by therealnoskill** [comment]
sound now working but i dont have lights na no menu like in original els

**Comment by matsn0w** [comment]
This sounds like user error, and not a bug. Please find help via the Discussions section or my Discord server: https://matsn0w.dev/discord
