### ISSUE TITLE
light system

### ISSUE THREAD

**Issue by Trko0045** [matsn0w/IIS-EmergencyLS-ELS-FiveM#187]
there is no way to change the keybinds 
and even i i do it in settings the Y key is still the original emergency key instead of it all being under Q for me

we are using Danish vehicles and there are no extra lights or traffic advisors on the cars
is there a way i can force the keybinds ?

**Comment by matsn0w** [comment]
Hi, since v2.2.0, you can change the default keybindings. See https://github.com/matsn0w/MISS-ELS/pull/109

**Comment by Trko0045** [comment]
What i mean. I want to decide keybinde server side

rn the whole script is conflicting and when disabling Q lights the emergency lights in game are toggeld and need to Press Y to disable th again

**Comment by Trko0045** [comment]
Same goes for Q key 

when pressed lights are on but vehicles don’t pull over until you press Y 

and again when pressing Q off 
You need to press Y to untoggle people from pulling over since it looks like the game only activates emergency when Y is on not Q 

and I only want one key for it all, server sided so all people know to just press Q for the lights system

**Comment by Trko0045** [comment]
I can use sirens in both Q activated and Y 
So it is just like script is dublicating keybinds and there is a bug or smth

**Comment by matsn0w** [comment]
I'm sorry, that isn't possible anymore. It was, so you could have a look at https://github.com/matsn0w/MISS-ELS/pull/109 and revert those changes yourself

**Comment by Trko0045** [comment]
Ok. Thanks so Munch for the answers

Is there a Quick Way to combone Y and Q functins do bolt Q is needed for
emergency Lightning

Med venlig hilsen / Best regards

*D.P.*


tors. 8. aug. 2024 kl. 07.19 skrev Bart Scholtus ***@***.***>:

**Comment by matsn0w** [comment]
Not that I know off.
